### ISSUE TITLE
[Feature Request] Address length should not be a feature

### ISSUE THREAD

**Issue by macalinao** [move-language/move#179]
# 🚀 Feature Request

Address length should be a generic [typenum](https://docs.rs/typenum/latest/typenum/) rather than a feature.

## Motivation

There are three standards of addresses used across various Move chains. Managing three sets of binaries is cumbersome. We also need to pass the `address20`. `address32`, etc. features across the stack.

## Pitch

**Describe the solution you'd like**
Use typenums to represent the address length, and code should be written with the typenums in mind. This would allow the same code to work across multiple platforms.

**Describe alternatives you've considered**
We can build three versions of each library and write a wrapper CLI which delegates commands to the correct binary.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes

## Additional context

N/A

**Comment by tnowacki** [comment]
We had discussed this and did not want to go the route of making `address` generic, as it would affect almost every aspect of the compiler + the vm. In other words, it would too big of an ergonomic strain across the code base.
Also, we did not want to make addresses dynamically sized (i.e. a `Vec<u8>` instead of an array `[u8; ADDRESS_LENGTH]`).

That being said, we weren't super pleased with the cargo feature solution. 
If you have an alternative (that isn't const generics or `Vec<u8>`), I'd happily review the PR. But it would probably be best to start with a small example in this issue first :)
