### ISSUE TITLE
[Feature Request] u256 is needed

### ISSUE THREAD

**Issue by guotie** [move-language/move#382]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

u256 is needed.

## Pitch

**Describe the solution you'd like**

u256 is needed.

**Comment by vgao1996** [comment]
Yeah we've discussed this before and everyone agreed we would want u256. I hope we'll have someone available to work on this soon... 

Another problem is that BCS doesn't support u256 yet and we need to get that resolved soon

**Comment by lerencao** [comment]
sir, also, u32, and i8, i32, i64, i128, etc.

**Comment by wrwg** [comment]
The Move maintainers have decided against signed integers for now, but the remaining unsigned are planned to come.

**Comment by vgao1996** [comment]
> It would be nice if we can convert address and u256 interchangeably.

This is an interesting point. I definitely agree that it would be helpful to have more conversion functions in the stdlib (e.g. `u64 <=> vector<u8>`). 

`address` would be a tricky one however, since its length is currently determined by a Rust feature flag. I'm not totally sure how we should handle this in the Move stdlib at this moment. Maybe in the short term, we'll just have to rely on each platform to offer its own conversion function?

**Comment by guotie** [comment]
u192 is an alternative to u256

**Comment by 0xys** [comment]
To support u256, are you going to add new Move VM bytecode?

**Comment by wrwg** [comment]
Yes, we want to support them natively like the other ints.

**Comment by sblackshear** [comment]
This is an approved feature awaiting implementation https://github.com/move-language/move/issues/453
