### ISSUE TITLE
[evm] `npx hardhat test` get affected by previous Move packages in a different git branch

### ISSUE THREAD

**Issue by junkil-park** [move-language/move#47]
See the error log:

```
$ npx hardhat test
An unexpected error occurred:

[Error: ENOENT: no such file or directory, stat '/Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/ERC721Mock/Move.toml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/ERC721Mock/Move.toml'
}
```

`contracts/ERC721Mock` does not exist in this branch. It did in a different branch. However, it complains.

**Comment by vgao1996** [comment]
This is caused by `move package build` not cleaning up old artifacts. I'll put up a patch to address this and https://github.com/move-language/move/issues/27 together as the underlying logic is related.

More precisely, `move package build --arch ethereum` should check if there are any existing artifacts before rebuilding:
1. If all artifacts are newer than the source, then it should do nothing
2. If any of the artifacts is older than the source, then it should delete all existing artifacts and rebuild everything
