### ISSUE TITLE
[Bug]  INVALID_LOOP_BREAK occur when verifying a correct code

### ISSUE THREAD

**Issue by lerencao** [move-language/move#496]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```move
module bug_report::test_case {
    public fun test_loop(a: u64): u64 {
        if (a == 2) {
            1
        } else if (a == 3) {
            let i = 0;
            let ret = 0;
            while (i < a) {
                ret = ret + i;
                i = i+1
            };
            ret
        }
        else {
            abort 10000
        }
    }
}
```

**Stack trace/error message**

`move  sandbox publish` output:

``` 
Publishing failed with unexpected error INVALID_LOOP_BREAK
```

## Additional context

related issue https://github.com/diem/diem/issues/8220

**Comment by tnowacki** [comment]
This is a good bug. Thanks for finding and reporting!

**Comment by jolestar** [comment]
This bug looks so familiar, and I realized that I reported this bug a year ago as well

**Comment by tnowacki** [comment]
> This bug looks so familiar, and I realized that I reported this bug a year ago as well

Do you have a link?

**Comment by tnowacki** [comment]
To be clear, this is likely a bug with the compiler, not with the bytecode verifier.

**Comment by amnn** [comment]
I had a look at the disassembly for the test case, and I can see why the verifier is failing (explained below).  There may be potential to improve the verifier here, as well as the compiler, depending on the intent behind this check which someone else will have to fill me in on.

## Issue

Looking at the disassembly or CFG (below) there's only one back edge: an unconditional branch from offset 30 to 17.  `check_breaks` makes sure that if you jump out of a loop, you only jump one instruction out (a `break`), but this conflicts with the unconditional branch from offset 21 to 33 which exits the loop.

## Motivation for this check

My understanding from reading the code is that `control_flow.rs` tries to check two properties (also shared as diagrams, below):
1. Loops are well nested (`check_continues`/`check_breaks`/`check_no_loop_splits`)
2. Loops don't nest too deeply (`check_loop_depth`)

These conditions are properties of the code's basic blocks but are written in terms of code offsets which imposes an additional layout assumption (i.e. that the compiler lays blocks out in a [weak-topological ordering](https://pages.cs.wisc.edu/~elder/stuff/bourdoncle.pdf)).

My thinking is that the additional layout assumption is not necessary for correctness, but that's where I need help from folks familiar with the history of the project (cc @tnowacki, @sblackshear).

Incidentally, there are some [patterns](https://www.wikiwand.com/en/Duff%27s_device) in other languages that intentionally compile to the kind of tangled CFG that this check eliminates, so I'm also curious what the motivation behind check (1) is as well -- is it to support check (2)?

## Possible Fixes

- If my thinking is right, it should be fairly straightforward to fix the verifier by having it think in terms of basic blocks.
- I also noticed that the bytecode is quite 'Branch'-y, it makes heavy use of unconditional branches which gives the compiler freedom to lay the blocks out how it likes and get into this position.  There's a potential opportunity to optimise this so the compiler leverages fallthroughs as much as possible.  I've attached another "less Branch-y" CFG below to show what that might look like, and it wouldn't have exhibited this issue, but I don't think it's the root cause here.
- Finally, we can also fix this in the compiler, appeasing the verifier by introducing a trampoline block that sits just outside the loop, which all breaks will jump to, but this feels like over-fitting the spec to me.

<details><summary><strong>Disassembly</strong></summary>

The bytecode for the above (built and disassembled using `move` @ move-language/move@db9b8cb29) looks like this:

```
// Move bytecode v5
module 0.test_case {


public test_loop(a: u64): u64 {
L0:	%#2: u64
L1:	i: u64
L2:	ret: u64
B0:
	0: CopyLoc[0](a: u64)
	1: LdU64(2)
	2: Eq
	3: BrTrue(5)
B1:
	4: Branch(8)
B2:
	5: LdU64(1)
	6: StLoc[2](%#2: u64)
	7: Branch(37)
B3:
	8: CopyLoc[0](a: u64)
	9: LdU64(3)
	10: Eq
	11: BrTrue(13)
B4:
	12: Branch(31)
B5:
	13: LdU64(0)
	14: StLoc[3](i: u64)
	15: LdU64(0)
	16: StLoc[4](ret: u64)
B6:
	17: CopyLoc[3](i: u64)
	18: CopyLoc[0](a: u64)
	19: Lt
	20: BrTrue(22)
B7:
	21: Branch(33)
B8:
	22: MoveLoc[4](ret: u64)
	23: CopyLoc[3](i: u64)
	24: Add
	25: StLoc[4](ret: u64)
	26: MoveLoc[3](i: u64)
	27: LdU64(1)
	28: Add
	29: StLoc[3](i: u64)
	30: Branch(17)
B9:
	31: LdU64(10000)
	32: Abort
B10:
	33: MoveLoc[4](ret: u64)
	34: StLoc[1](%#1: u64)
	35: MoveLoc[1](%#1: u64)
	36: StLoc[2](%#2: u64)
B11:
	37: MoveLoc[2](%#2: u64)
	38: Ret
}
}
```
</details>

<details><summary><strong>CFG</strong></summary>
<img src="https://user-images.githubusercontent.com/332275/192813447-bca91bff-09d8-43ce-bb3b-86bf2e29c407.png" alt="CFG" />
</details>

<details><summary><strong>Checks</strong></summary>
<img src="https://user-images.githubusercontent.com/332275/192812856-6f22ae9d-521a-4f33-a677-b5605b9447ce.png" alt="Checks"/>
</details>

<details><summary><strong>CFG: Less Branch-y</strong></summary>
<img src="https://user-images.githubusercontent.com/332275/192813545-2fea8cc6-5c87-4555-b6e0-7ffd23b136a5.png" alt="less branch-y CFG" />
</details>

**Comment by amnn** [comment]
@tnowacki and I chatted about this offline -- there is an additional condition that may be worth preserving -- that back-edges in the bytecode (jumping to a lower offset) only get used for true loops.  This assumption can simplify other parts of the verifier. The current check does guarantee this as part of `check_continues`, and a more general version that only cares about basic blocks won't, but it should be possible to additionally track that.

I'll take a look at tweaking `control_flow.rs` to accept this test case (without allowing non-loop back-edges).

**Comment by amnn** [comment]
Discussed the plan of action with @meng-xu-cs.  The fix will preserve the well-nested loops check, but relax the restriction equating backward jumps with loop back edges, by making CFG generation more robust to not require it.
