### ISSUE TITLE
[Move Prover] A bug in struct invariant

### ISSUE THREAD

**Issue by junkil-park** [move-language/move#594]
Prover should fail on the following example because `push_1` violates the struct invariant. However, Prover succeeds(?) proving this, which raises a soundness concern.

```
module 0x42::struct_invariant_bug {
    use std::vector;

    struct S {
        v: vector<u64>,
    }
    spec S {
        invariant len(v) == 0;
    }

    public fun empty(): S {
        S { v: vector::empty<u64>() }
    }

    public fun push_1(s: &mut S) {
        vector::push_back(&mut s.v, 1);
    }
}
```

**Comment by meng-xu-cs** [comment]
As we discussed, succeeding in proving this `push_1` is expected behavior as struct invariants only get checked when the borrow ends. At the end of the `push_1` function, the argument `s: &mut S` is still being mutably borrowed, and hence, the assertion for the invariant is not even instrumented, let alone checked.

**Comment by junkil-park** [comment]
Thank you for the clarification! I now understand that this is not an implementation bug because it's designed that way. However, could this be a design bug? It's because the users without knowing the implementation details would expect that the example above fails to prove. (@rahxephon89)

**Comment by junkil-park** [comment]
This has been resolved.
