### ISSUE TITLE
[Prover] internal boogie error raised when using Table and struct invariant together

### ISSUE THREAD

**Issue by junkil-park** [move-language/move#680]
## Reproduce
Run Prover for the following example:
```
module 0x42::table_bug {
    use aptos_std::simple_map;

    struct R has key {
        map: simple_map::SimpleMap<address, S>
    }

    struct S has store {
        value: u64
    }
    spec S {
        invariant value >= 0;
    }

    fun f() acquires R {
        let _ = &borrow_global<R>(@0x42).map;
    }
}
```

Prover produces the following output:
```
$ move prove -t table_bug
[INFO] preparing module 0x42::table_bug
[INFO] transforming bytecode
[INFO] generating verification conditions
[INFO] 1 verification conditions
[INFO] running solver
Error: [internal] boogie exited with compilation errors:
output.bpl(1637,71): error: ";" expected
output.bpl(1637,92): error: ")" expected
2 parse errors detected in output.bpl
```

## Expected Output
Prover produces no internal error.

**Comment by meng-xu-cs** [comment]
This is a much deeper issue than it appears and probably requires several PRs to handle it.

The issue is that currently, instrumentation of data invariants in the new `map` intrinsic type is missing. Therefore, if a `struct SimpleMap<K, V>` is an intrinsic `map` type, and `K` and/or `V` has data invariants, then we need to augment the `WellFormed` assumption to add that
- for each `key: K` in `SimpleMap<K, V>`, `WellFormed(key) && DataInvariantOfKHold(key)`
- for each `val: V` in `SimpleMap<K, V>`, `WellFormed(val) && DataInvariantOfVHold(val)`

Or, alternatively
- for each `(key, val): (K, V)` in `SimpleMap<K, V>`, `WellFormed(key) && DataInvariantOfKHold(key) && WellFormed(val) && DataInvariantOfVHold(val)`

Currently, we don't have any constructs to model this `forall` behavior, which makes solving this issue harder than it appears. We have a similar construct to model `forall e: T :: vector : Vec T`, which can be a good reference point.
